# Generated by Django 3.2.9 on 2022-03-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('now', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pemailassword',
            new_name='password',
        ),
    ]
