# Generated by Django 3.2.9 on 2022-05-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.IntegerField(max_length=11)),
                ('acCnt', models.IntegerField(max_length=11)),
                ('submitCnt', models.IntegerField(max_length=11)),
                ('acList', models.TextField(max_length=5000)),
                ('miscCnt', models.IntegerField(max_length=11)),
                ('cryptocnt', models.IntegerField(max_length=11)),
                ('webcnt', models.IntegerField(max_length=11)),
                ('pwncnt', models.IntegerField(max_length=11)),
                ('recnt', models.IntegerField(max_length=11)),
                ('test', models.TextField(max_length=5000)),
                ('testamount', models.IntegerField(max_length=11)),
            ],
            options={
                'db_table': 'question_user',
            },
        ),
    ]
